#!/bin/bash
echo "Enter number range:"
read user_number
number_array=()
for (( i=1; i<=$user_number ; i++ )); do
	number_array+=($i)
done
 for (( i=0; i<$user_number ; i++ )); do
        #echo ${number_array[$i]}
	if [ $((${number_array[$i]}%3)) -eq 0 ]; then
		echo "${number_array[$i]} is Fizz"
	elif [ $((${number_array[$i]}%5)) -eq 0 ]; then
		echo "${number_array[$i]} is Buzz"
	fi
done
