#!/bin/bash
read filename
fileowner=$(ls -l $filename | awk '{ print $3 }')

if [ "$USER" != "$fileowner" ]; then
        echo "Script must be run as owner"
	sudo chmod 700 $filename
elif [ "$USER" == "$fileowner" ]; then
	echo "$USER you are the owner"
	sudo chmod 744 $filename
fi
