#!/bin/bash
echo "Enter number range:"
read user_number
for i in $(seq 0 1 $user_number) 
do
        #echo ${number_array[$i]}
	if [ $($i%3) -eq 0 ]; then
		echo "$i is Fizz"
	elif [ $($i%5) -eq 0 ]; then
		echo "$i is Buzz"
	fi
done
